# Generated by Django 4.0.4 on 2022-04-27 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sana', models.DateField()),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_ustoz', to='App.ustoz')),
            ],
        ),
    ]
