# Generated by Django 4.0.4 on 2022-04-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_fan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='sana',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='yonalish',
        ),
        migrations.AddField(
            model_name='fan',
            name='cod',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fan',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='fan',
            name='vaqt',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fan',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('fanlar', models.ManyToManyField(to='App.fan')),
                ('ustozlar', models.ManyToManyField(to='App.ustoz')),
            ],
        ),
    ]
