# Generated by Django 4.0.4 on 2022-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_fan_sana_remove_fan_yonalish_fan_cod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fan',
            name='vaqt',
            field=models.CharField(max_length=30),
        ),
    ]
