# Generated by Django 4.0.4 on 2022-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_fan_is_active_alter_fan_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='vaqt',
            field=models.DateField(max_length=30),
        ),
    ]
